### ISSUE TITLE
Class 'OCA\ImageSize\Hook\FileHook' not found

### ISSUE THREAD

**Issue by oparoz** [harshjv/owncloud-imagesize-app#1]
This is what I get when I upload a file

```
PHP","message":"Class 'OCA\\ImageSize\\Hook\\FileHook' not found at \/customapps\/imagesize\/appinfo\/application.php#27"
```

@harshjv - Have you tested the app by installing it? If yes, any idea why I'm getting this error?

**Comment by harshjv** [comment]
@oparoz Yes, I've tested my application on a fresh installation and it worked well.

<img width="469" alt="screen shot 2016-03-22 at 1 01 32 am" src="https://cloud.githubusercontent.com/assets/2311316/13931509/abd6dd72-efc9-11e5-8769-76cfc64eeb88.png">

Just a thought. I think you have moved application to a custom directory _`(ownCloud/customapps)`_ rather than `ownCloud/apps`, which do not follow ownCloud's class loader. https://doc.owncloud.org/server/9.1/developer_manual/app/classloader.html

**Comment by harshjv** [comment]
@oparoz or any other thoughts? To me, this issue is more related to automatic class loading and directory structure.

**Comment by oparoz** [comment]
@harshjv - Thanks for confirming.

My configurations is actually supported for apps:
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html#apps

I think you're right, it's probably related to the class loader, but I haven't figured out what the loader doesn't like.

Is your IDE reporting any warnings or even errors?

**Comment by oparoz** [comment]
What is your app named in your apps folder in ownCloud?

**Comment by harshjv** [comment]
@oparoz - okay

My app folder's name is **imagesize**. _`(ownCloud/apps/imagesize)`_

No, IDE isn't reporting any errors or warnings for this.

**Comment by oparoz** [comment]
OK, I'm using the same app name.

**Comment by oparoz** [comment]
Found the problem.
You should not use capital letters in your filenames.

**Comment by harshjv** [comment]
I tried it in my another installation, and it worked well there too.

My environment is;
- PHP 5.5.30
- Apache 2.4.16
- OS X

**Comment by harshjv** [comment]
Ah, because OS X's default file system is case insenstive, so it didn't report any error here.

I'll rename it and push changes.

**Comment by oparoz** [comment]
:+1:

**Comment by oparoz** [comment]
Not so fast, there are more files with capital letters ;)

Also, if you can, try to have access to a VM or a cheap server. OSX is not really supported as a server.

**Comment by harshjv** [comment]
Oh yes. `ImageSize` and `ImageSizeMapper` classes. Working on it... :smile:

**Comment by harshjv** [comment]
I got it. I'll use a VM then.

**Comment by oparoz** [comment]
Works as expected now. I was able to see the image dimensions in the database.

**Comment by harshjv** [comment]
@oparoz thanks for identifying the bottleneck :smile:
